from __future__ import annotations

import sys
import tempfile
import unittest
from pathlib import Path


VIEWER_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(VIEWER_ROOT / "src"))

from openlab_viewer.data_reader import (  # noqa: E402
    DataFormatOptions,
    DataReadError,
    detect_data_format,
    parse_line_ranges,
    read_data,
)


class DataReaderTests(unittest.TestCase):
    def test_detects_openlab_data_section(self) -> None:
        content = "[Header]\nSample\n[Data]\nTime,Value\n0,1\n1,2\n"
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "sample.dat"
            path.write_text(content, encoding="utf-8")
            self.assertEqual(detect_data_format(path), DataFormatOptions.openlab())

    def test_detects_tabular_text_after_metadata(self) -> None:
        content = "metadata\nmode\tvalue\n1\t2\n3\t4\n5\t6\n"
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "sample.text"
            path.write_text(content, encoding="utf-8")
            options = detect_data_format(path)
            self.assertEqual(
                options,
                DataFormatOptions(
                    mode="custom",
                    header_line=2,
                    data_start_line=3,
                    delimiter="tab",
                    encoding="auto",
                ),
            )
            self.assertEqual(len(read_data(path, options).rows), 3)

    def test_ambiguous_text_requires_manual_format_settings(self) -> None:
        content = "metadata\none line\nanother line\n"
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "ambiguous.text"
            path.write_text(content, encoding="utf-8")
            self.assertIsNone(detect_data_format(path))

    def test_detects_numeric_text_without_header(self) -> None:
        content = "1;2\n3;4\n5;6\n"
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "sample.text"
            path.write_text(content, encoding="utf-8")
            options = detect_data_format(path)
            self.assertEqual(options.header_line, None)
            self.assertEqual(options.data_start_line, 1)
            self.assertEqual(options.delimiter, "semicolon")

    def test_parse_line_ranges(self) -> None:
        self.assertEqual(parse_line_ranges("1-3, 3, 7, 9-10"), (1, 2, 3, 7, 9, 10))
        with self.assertRaises(ValueError):
            parse_line_ranges("4-2")

    def test_custom_delimited_file_preserves_physical_lines(self) -> None:
        content = (
            "instrument export\n"
            "# generated by test\n"
            "time;signal;label\n"
            "0;1.5;first\n"
            "ignore this row\n"
            "1;2.5;second\n"
        )
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "sample.csv"
            path.write_text(content, encoding="utf-8")
            options = DataFormatOptions(
                mode="custom",
                data_start_line=4,
                header_line=3,
                delimiter="semicolon",
                comment_lines=(5,),
                comment_prefixes=("#",),
                encoding="utf-8",
            )
            document = read_data(path, options)
        self.assertEqual(document.columns, ("time", "signal", "label"))
        self.assertEqual(document.rows, (("0", "1.5", "first"), ("1", "2.5", "second")))
        self.assertEqual(document.source_line_numbers, (4, 6))
        self.assertEqual(document.numeric_series("signal", "time"), ((0.0, 1.5), (1.0, 2.5)))

    def test_custom_file_without_header_keeps_first_data_row(self) -> None:
        content = "metadata\n1,2\n3,4\n"
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "sample.txt"
            path.write_text(content, encoding="utf-8")
            document = read_data(
                path,
                DataFormatOptions(
                    mode="custom",
                    data_start_line=2,
                    delimiter="comma",
                    comment_lines=(1,),
                    encoding="utf-8",
                ),
            )
        self.assertEqual(document.columns, ("Column 1", "Column 2"))
        self.assertEqual(document.rows, (("1", "2"), ("3", "4")))
        self.assertEqual(document.source_line_numbers, (2, 3))

    def test_openlab_data_section(self) -> None:
        content = (
            "[Header]\n"
            "Sample\n"
            "[Data]\n"
            "Time(s),Voltage\n"
            "0,1\n"
            "1,2\n"
        )
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "sample.dat"
            path.write_text(content, encoding="utf-8")
            document = read_data(path, DataFormatOptions.openlab())
        self.assertEqual(document.columns, ("Time(s)", "Voltage"))
        self.assertEqual(document.source_line_numbers, (5, 6))
        self.assertEqual(document.numeric_series("Voltage", "Time(s)"), ((0.0, 1.0), (1.0, 2.0)))

    def test_openlab_reader_keeps_multiline_fields_and_extra_columns(self) -> None:
        content = (
            "[Data]\n"
            "Time,Comment\n"
            "0,\"first line\n"
            "second line\",7\n"
        )
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "multiline.dat"
            path.write_text(content, encoding="utf-8")
            document = read_data(path, DataFormatOptions.openlab())
        self.assertEqual(document.columns, ("Time", "Comment", "Extra 3"))
        self.assertEqual(document.rows, (("0", "first line\nsecond line", "7"),))
        self.assertEqual(document.source_line_numbers, (3,))

    def test_encoding_selection(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "utf16.txt"
            path.write_text("x;y\n1;2\n", encoding="utf-16")
            document = read_data(
                path,
                DataFormatOptions(
                    mode="custom",
                    header_line=1,
                    data_start_line=2,
                    delimiter="semicolon",
                    encoding="utf-16",
                ),
            )
        self.assertEqual(document.columns, ("x", "y"))
        self.assertEqual(document.rows, (("1", "2"),))

    def test_automatic_read_rejects_unterminated_final_line(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "live.csv"
            path.write_bytes(b"x,y\n1,2")
            options = DataFormatOptions(
                mode="custom",
                header_line=1,
                data_start_line=2,
                delimiter="comma",
                encoding="utf-8",
            )
            self.assertEqual(len(read_data(path, options).rows), 1)
            with self.assertRaises(DataReadError):
                read_data(path, options, allow_unterminated_last_line=False)

    def test_automatic_utf16_read_accepts_a_complete_newline(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "live.txt"
            path.write_text("x;y\n1;2\n", encoding="utf-16")
            options = DataFormatOptions(
                mode="custom",
                header_line=1,
                data_start_line=2,
                delimiter="semicolon",
                encoding="utf-16",
            )
            document = read_data(
                path,
                options,
                allow_unterminated_last_line=False,
            )
        self.assertEqual(document.rows, (("1", "2"),))

    def test_invalid_extra_field_is_rejected_when_header_is_present(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "invalid.csv"
            path.write_text("x,y\n1,2,3\n", encoding="utf-8")
            options = DataFormatOptions(
                mode="custom",
                header_line=1,
                data_start_line=2,
                delimiter="comma",
                encoding="utf-8",
            )
            with self.assertRaises(DataReadError):
                read_data(path, options)

    def test_custom_rows_must_keep_the_established_width(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "invalid.csv"
            path.write_text("1,2\n3\n", encoding="utf-8")
            options = DataFormatOptions(
                mode="custom",
                data_start_line=1,
                delimiter="comma",
                encoding="utf-8",
            )
            with self.assertRaises(DataReadError):
                read_data(path, options)

    def test_custom_multiline_quoted_record_is_reported(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "multiline.csv"
            path.write_text("x,y\n1,\"first line\nsecond line\"\n", encoding="utf-8")
            options = DataFormatOptions(
                mode="custom",
                header_line=1,
                data_start_line=2,
                delimiter="comma",
                encoding="utf-8",
            )
            with self.assertRaisesRegex(DataReadError, "multiline quoted records"):
                read_data(path, options)


if __name__ == "__main__":
    unittest.main()
